### ISSUE TITLE
It's not an issue, it's a big THANK YOU!

### ISSUE THREAD

**Issue by 925-Studio** [TechUnRestricted/windiskwriter#11]
Here is the thing. I installed Windows 11 Pro on my new PC but I replaced it with Linux Mint yesterday. Today I was trying install Windows again (don't ask me why) but it didn't work. I always stucked on 'can't find the drivers for my SSD drive'. The problem was I used terminal and Etcher to create the installation USB and they seems not capable to do the job properly on my Mac Mini M1. Then I find your app, now the installation has already finished when I'm still typing. You're the best! Thank you for making this great app.

**Comment by TechUnRestricted** [comment]
I'm glad to hear that **WinDiskWriter** was helpful in resolving your issue with reinstalling Windows on your PC!
If you have any more questions or need further assistance in the future, feel free to reach out.
Enjoy using your freshly installed operating system!
