### ISSUE TITLE
Cant verify the image i just downloaded from the offical site [Windows 10]

### ISSUE THREAD

**Issue by jncheung** [TechUnRestricted/WinDiskWriter#12]
<img width="287" alt="image" src="https://github.com/TechUnRestricted/windiskwriter/assets/30644696/86b64b67-6a9d-4dce-a58c-4d3506e1b666">

I got the message right after i clicked the start button

The ISO what i am using is : Win10_22H2_Chinese_Traditional_x64v1

**Comment by TechUnRestricted** [comment]
<div class="issue">
    <p>It appears that the <code>hdiutil</code> on your Mac is unable to mount the downloaded Windows 10 image due to a specific system issue <b>that is beyond my control</b>.</p>
<p><b>Please follow these steps:</b></p>
    <ol>
        <li>Manually attempt to mount the Windows image by <b>double-clicking</b> on it.<br><i>This step is required to verify if the image is even mountable.</i></li>
        <li>If the image mounts successfully, proceed to use <b>WinDiskWriter</b> and <b>select the mount path</b><br>(Example: <code>/Volumes/Windows_Image</code>) (not the .iso itself) for the <code>Windows Image</code> text field.</li>
        <li>If the image does not mount, <b>a system reboot of your Mac is recommended</b>.</li>
    </ol>
</div>

**Comment by vinceroti** [comment]
Just as a note, I got this error because I had the windows ISO mounted. Unmounting it fixed it.

**Comment by TechUnRestricted** [comment]
@vinceroti Got it.
That's an error on <code>hdiutil</code> macOS built-in binary side.

I'll think about how can I minimize the occurrence of it, since I'm doing a complete rewrite of WinDiskWriter from Objective-C to Swift. So some new logic can be added.

Thank you very much for the report! 👍

**Comment by vinceroti** [comment]
@TechUnRestricted 

Thank you very much for this tool!!

**Comment by jncheung** [comment]
Thanks so much both. i got it fixed as well after unmount.
