### ISSUE TITLE
No Option On Start Up

### ISSUE THREAD

**Issue by potionseller1** [TechUnRestricted/WinDiskWriter#14]
I cannot for the life of me get this working -- maybe I need super noob instructions, since the regular noob ones aren't doing it for me.

I have the USB formatted with WinDIskWriter and everything worked fine -- said image writing was successful. 

When I go to boot my MacBook - there just isn't an option to boot anything but the base OS. I'm running a Macbook Pro, M3, Sonoma 14.1

I went and checked to make sure my USB is discoverable as external, and it is. Went into Start-Up Security and changed everything to low just in case that worked -- it did not.

How do I boot this thing?? lol

**Comment by TechUnRestricted** [comment]
You can't run Windows on Apple silicon as a standalone OS. You need an Intel / AMD computer for it.  

Your options are limited to a virtual machine (e.g. Parallels).
