### ISSUE TITLE
Windows 7, stops/stalls on boot in old imac (late 2009)

### ISSUE THREAD

**Issue by pladekusken** [TechUnRestricted/WinDiskWriter#15]
Hi

(I have created bootcamp to install windows - but need to start with windows 7 and test some drivers/programs etc)

I have tested the tool with Windows 7 - but the mac (imac 27 late 2009) stalls/freezes after choosing the efi boot usb on startup.
If the image is burned to a DVD it can boot up.
.. on a windows 10 image to USB it works ...

Is this a known issue - can anything be done in this matter ?
It could be VERY nice if you could fix it for windows 7 - my impression is that then this tool would be extra good ;-)

/ p

**Comment by TechUnRestricted** [comment]
Hello!
Could you please send a screenshot from WinDiskWriter with options you've used for creating a Windows 7 bootable USB?
Thanks.

**Comment by TechUnRestricted** [comment]
@pladekusken Got it.
Let's try the following options:
![Untitled](https://github.com/TechUnRestricted/WinDiskWriter/assets/83237609/295bd1f9-8612-4e57-bf04-39a672d16633)

Then wait until the end of the writing process.
Go to <code>Your_USB_Drive/EFI/BOOT/<b>bootx64.efi</b></code> and remove it.

Now you should be able to boot.

**Comment by pladekusken** [comment]
Finishes and prompts with warning: The disk you inserted was not readable by this computer
See attached screenshot
![image](https://github.com/TechUnRestricted/WinDiskWriter/assets/66180626/12edd83a-5036-4523-b50b-020fbbfca854)
I am not able to see or edit files?
If I try to enter boot menu on start up - there is not USB ...

**Comment by TechUnRestricted** [comment]
That's strange.
Let's check if Legacy Bootloader files are not corrupted.

Go to `~/Library/Caches/WinDiskWriter/gru4dos` **(Finder → Go → Go to Folder)** and attach here the following files:
* grldr
* grldr.mbr
* menu.lst

**Comment by pladekusken** [comment]
I tried to create the USB on another Mac (Mac Mini Late 2012 - Catalina) with your suggestion for parameters - and it did not end with the warning/error - I could also enter the USB and remove the file you suggested.

**But** on reboot: the bootmenu does not even see the USB drive (applies to both Macs).

PS: I also did try to boot with normal (without: Install Legacy BIOS Boot Sector) settings on the other Mac that also freezes.

**Comment by TechUnRestricted** [comment]
Hi! It seems like that your old iMac 2009 is not capable of booting in `Legacy BIOS Mode` from USB devices, so I can't really help you in this situation.

Speaking about EFI booting, Windows 7 is a very old OS, so it has very basic EFI support.
It works for most PC hardware, but Macs are the exception.

**Comment by pladekusken** [comment]
Hi again - Seems like it - thanks for your support.
/ p
