### ISSUE TITLE
Windows 10 - "Can't verify this Image."

### ISSUE THREAD

**Issue by mccombs** [TechUnRestricted/WinDiskWriter#24]
The exit status of hdiutil was not EXIT_SUCCESS.
[hdiutil: attach failed - Resource temporarily unavailable]

![Screenshot 2024-09-27 at 2 29 02 PM](https://github.com/user-attachments/assets/0eccae19-3af6-41fd-a576-b02d0e904405)

**Comment by TechUnRestricted** [comment]
This issue is caused by macOS built-in “hdiutil” binary.
Try to mount Windows image manually and then start the process again.

**Comment by mccombs** [comment]
Worked like a charm! Thanks for the quick response.
