### ISSUE TITLE
This Software fix the problem of SSD not showing up

### ISSUE THREAD

**Issue by marceloangelim** [TechUnRestricted/windiskwriter#3]
I was having a strange problem that the installation of windows 10 and 11 was not recognizing any partition of my ssd. I was trying to make dual boot  in my steam deck.

The first thing a can mention is that a was using balena etcher on a Mac OS to create this windows bootable flash drive. Balena etcher was showing a pop-up saying something about a missing bootable partition table or something like that.

This happened with the image o windows 10 and 11.

After a flashed the windows 11 image using WinDiskWriter with the patch  o TPM the problem was solved.
I am sharing this piece of information for my steam deck colleagues out there so they know  that using  a Mac to create the windows bootable USB with balena etcher may need to use WinDiskWriter to properly flash their dual boot.

this may even help those that just need a clean install of windows but the SSD don't show up.

**Comment by TechUnRestricted** [comment]
Hi! Thank you for your positive feedback.
I'm glad that you have successfully installed Windows on your device using my software :)

I'l try to add some more functionality to WinDiskWriter such as MBR Legacy Boot mode and the patch for skipping the mandatory Microsoft Account Login step on Windows 11.

Stay tuned for the updates.
But unfortunately, I'm too busy with my studies at uni right now :(
