### ISSUE TITLE
noob: how do I actually run the program?

### ISSUE THREAD

**Issue by nockeight** [TechUnRestricted/windiskwriter#4]
hi,

apologies but downloading the zip file I can't for the life of me figure out how to run the software.

apologies on the noob question.

thanks
Nock

**Comment by TechUnRestricted** [comment]
<p>Hi Nock!</p>
<p>Sorry if something wan&#39;t clear for you.
Let me explain everything step-by-step.</p>
<ol>
<li><p>Download the Windows Install Image with <strong>.iso</strong> extension</p>
<ul>
<li><p>From the official Microsoft Website</p>
<ul>
<li><p><a href='https://www.microsoft.com/en-us/software-download/windows10ISO'>Windows 10</a></p>
</li>
<li><p><a href='https://www.microsoft.com/software-download/windows11'>Windows 11</a></p>
<details>
  <summary>Download page example</summary>
  <img src="https://i.ibb.co/5G5zrtx/Untitled-x.png">
</details>
</li>
</ul>
</li>
<li><p>From the any source you want</p>
<ul>
<li><p>It can be any version of these supported Windows Versions:  </p>
<ol>
<li>Windows 11</li>
<li>Windows 10</li>
<li>Windows 8.1</li>
<li>Windows 8</li>
<li>Windows 7</li>
<li>Windows Vista</li>
</ol>
<p><sup>Just make sure that you download <strong>x64</strong> version for the UEFI-based computers.<br>
Legacy-BIOS support is not available yet.</sup></p>
</li>
</ul>
</li>
</ul>
</li>
</ol>
<ol start=2>
	<li>
		Get the latest version of <b>WinDiskWriter</b> from the <a href="https://github.com/TechUnRestricted/windiskwriter/releases/">Release</a> page.<br>
		<img width="214" alt="image" src="https://user-images.githubusercontent.com/83237609/275045385-616cd676-cfe6-40d9-8fe9-a76bb1fcc664.png">
		<ol>
			<li>Extract the archive by double-clicking on the downloaded .zip file <sup><sub><b>[If not done automatically by your browser]</b></sub></sup></li>
			<li>Do the "<b>Control + Mouse Click</b>" on the <b>WinDiskWriter</b> application.<br> <img width="314" alt="image" src="https://user-images.githubusercontent.com/83237609/275046073-5f2a19ac-2b3a-4330-817e-cea927afa467.jpg"> </li>
			<li> Due to the abcense of Apple Developer Signature in my App, you will see the following message:<br> <img width="372" alt="image" src="https://user-images.githubusercontent.com/83237609/275046224-06879ee6-46b6-4223-8ad9-a946a68692d5.png"><br> You need to do the <b>3<sup>rd</sup></b> step again. </li>
			<li> Now you should get the "<b>Open</b>" option:<br> <img width="372" alt="image" src="https://user-images.githubusercontent.com/83237609/275046718-3d346fe1-f6c8-40b4-a04f-7eb6d0591e34.png"><br> Click on it. </li>
		</ol>
	</li>
</ol>
<ol start='3' >
<li><p>Launch the <strong>WinDiskWriter</strong>.</p>
<ol>
<li><p>Choose the Windows image file that you downloaded earlier.</p>
</li>
<li><p>Select the destination device where you want to write the image.</p>
</li>
<li><p>Select the FAT32 file system for the best compatibility with EFI firmwares.</p>
</li>
<li><p>If you want to install Windows on a device that does not have a TPM 2.0 chip and/or Secure Boot support, you must enable the “Patch Installer Requirements” option.
<sup><em>(This operation requires approximately 5.5 GB of free disk space on your macOS device.)</em></sup></p>
<p><img width="280px" src="https://dev-to-uploads.s3.amazonaws.com/uploads/articles/bbpqf090eqsmiop9f0o0.png"></p>
</li>
<li><p>Click on the <strong>Start</strong> button.</p>
</li>
</ol>
</li>
</ol>
<p>&nbsp;</p>
<p>If everything went smoothly, you&#39;ll get the following message:</p>
<p><img width="280px" src="https://dev-to-uploads.s3.amazonaws.com/uploads/articles/sdezh9p96oc15y8yjb8y.png"></p>

**Comment by OptiPrim** [comment]
I'm starting to feel I have Github dyslexia.  Thanks for this, I still feel Github is overcomplicated for a pea brain like myself. I really appreciate your efforts in trying to explain the process.

**Comment by TechUnRestricted** [comment]
@OptiPrim 
At some point, I plan to create a website.
However, my current schedule is quite hectic as I’m juggling my studies with job applications.

**Comment by OptiPrim** [comment]
Hi, false alarm, sorry to bother you. It worked perfectly once I'd followed
the guide. It was such a relief to actually get my old PC working again.
Thank you so much!

**Comment by KastanDay** [comment]
I agree this would be helpful info in the readme, I'm a MacOS noob and didn't realize how to get around the "click the hidden open button" trick.

**Comment by TechUnRestricted** [comment]
Hi. Yeah, I think you’re right. I’ll update my readme.
Thank you!!
________________________________
Od: Kastan Day ***@***.***>
Wysłane: Tuesday, July 9, 2024 10:15:38 AM
Do: TechUnRestricted/WinDiskWriter ***@***.***>
DW: TechUnRestricted ***@***.***>; State change ***@***.***>
Temat: Re: [TechUnRestricted/WinDiskWriter] noob: how do I actually run the program? (Issue #4)


I agree this would be helpful info in the readme, I'm a MacOS noob and didn't realize how to get around the "click the hidden open button" trick.

**Comment by sanitybit** [comment]
For anyone that may need to script this for whatever reason, you can also:

`sudo xattr -r -d com.apple.quarantine {APP BUNDLE}`

e.g. ` sudo xattr -r -d com.apple.quarantine /Applications/WinDiskWriter.app`

**Comment by Aky97567** [comment]
On macOS Sequoia, to run unsigned apps:

- First run attempt fails
- Go to System Settings -> Privacy & Security
- Scroll to bottom and click "Open Anyway" for that specific app

**Comment by StuartRob** [comment]
> For anyone that may need to script this for whatever reason, you can also:
> `sudo xattr -r -d com.apple.quarantine {APP BUNDLE}`
> e.g. ` sudo xattr -r -d com.apple.quarantine /Applications/WinDiskWriter.app`

This worked for me in January 2025 on M1 pro Sequoia 15.2.

**Comment by citrus-fruit-lang** [comment]
Thanks for the instructions!

I've managed to get it running but when I select FAT32, it can never detect my 32GB and 8GB sandisk USBs. I get the error "Destination path does not exist."

But it can detect and write to them when I select ExFAT but my UEFI can't detect it. 

My UEFI can only detect FAT32. 

Has anyone run into this issue and found a solution?

**Comment by realchlorum** [comment]
Thanks so much!!! Finally a programm that worked. Ive been biting my ass of with a Win11 creation. I saw your comment on another website about this little project
