### ISSUE TITLE
No drives show up unless I select "Scan All Whole Disks" option

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [TechUnRestricted/windiskwriter#7]
My USB drives don't show up unless I select the "Scan All Whole Disks" option under Debug. I've tried with multiple USBs, they all have this issue.

I'm on a hackintosh (closest Mac equivalent is the iMac19,1) running Sonoma 14.2.1.

**Comment by TechUnRestricted** [comment]
I think there is an issue with your USB mapping.

Let’s debug it:
<ul>
<li>Open <code>Terminal.app</code></li>
<li>Run <code>diskutil list</code></li>
<li>Find your USB device and then run <code>diskutil info disk*</code> (where <code>*</code> — your disk number)</li>
</ul>

Send me the Terminal output.

I think your USB devices are marked as Internal and that’s why WinDiskWriter ignores them.
