### ISSUE TITLE
Need a windows 10 Recovery USB

### ISSUE THREAD

**Issue by go4d1** [TechUnRestricted/windiskwriter#9]
I am a professional Windows developer. I’ve been working on Windows on  Mac since 2010 - I have had a frequently  recurring problem - probably 20 times over the past 15 years - Somehow, I get a corrupt file in the Windows boot sector - On my old Mac Pro 2010  -running Windows 7, I could easily repair the Windows operating system with a recovery disk.  However, since updating to a Mac Pro 2019 - I have been unable repair the disk and have had t reinstall Windows 4 times already.  I am really at my wits end.

I’m hoping you can provide a bootable USB that will solve my problem.I tried donating $100 as a sign of good faith but all your Crypto accounts require downloading the app and creating an account.

My email appears at the bottom of this page: https://moirasmith.com/  I’ll arrange payment via PayPal or others.

There are many recovery disk offerings on eBay - but none that will work with Windows/Mac    -  I’m sure there would be a market for one.

**Comment by TechUnRestricted** [comment]
Greetings. I have sent you an e-mail regarding this matter.
Thank you.

**Comment by go4d1** [comment]
Vadim,
I was called to an early meeting tomorrow  Monday. - I’ll email you when I am available. I’m sure we’ll connect
Martin

**Comment by TechUnRestricted** [comment]
Ok, no problem.
You can message me in Skype when you’re free.

But we won't be able to call, just text.
